### ISSUE TITLE
Design the Button component

### ISSUE THREAD

**Issue by failuer** [alloverse/alloui-lua#4]
After trying out a ton of button behaviours during the research phase, it's time to condense the best of the best into the AlloUI button. How should it feel & function?

- Flat or 3d?
- square or rounded?
- What's the visual, sound and/or haptic feedback like on **hover** and **active** (down)?
- How should the above feedback change if the button is disabled?
- General look - colors, paddings, etc
- Typography: what should text on buttons look like?
- Iconography: what should icons on buttons look like?
- If a button has only an icon, would it display a label when hovering over the button? If so, where/how?
- If applicable, if a button would support displaying icon AND text at the same time, how would that look?

**Comment by failuer** [comment]
Is there a document somewhere with the guidelines/design specs that were decided on?

**Comment by dmjezewska** [comment]
https://www.figma.com/file/w70lob3WKO2feZz5jBGnW8/New-AlloUI?node-id=0%3A1

**Comment by dmjezewska** [comment]
model viewer issue

**Comment by dmjezewska** [comment]
waiting for color testing

**Comment by dmjezewska** [comment]
https://drive.google.com/file/d/17dBzUUZCChcUJew0nBMlUDXEiMRFSP6f/view button glb
