### ISSUE TITLE
Define a AlloUI color palette

### ISSUE THREAD

**Issue by failuer** [alloverse/alloui-lua#9]
Define colors for:
- [x] Primary button
- [x] Secondary button
- [x] Panels
- [ ] More to come during work on other UI issues, probably...

**Comment by dmjezewska** [comment]
figma file with finalized color palette: https://www.figma.com/file/w70lob3WKO2feZz5jBGnW8/New-AlloUI?t=cAiqzwL9qAqBeFHO-1

**Comment by dmjezewska** [comment]
screenshot of color palette with primary, secondary buttons palette

![Image](https://user-images.githubusercontent.com/33136939/204607700-f054816d-3f7a-496b-a704-479d64196ea8.png)

**Comment by dmjezewska** [comment]
![Image](https://user-images.githubusercontent.com/33136939/214114154-c94cbd49-1b4b-4d08-bf6c-de94114ce669.png)

updated color palette

**Comment by dmjezewska** [comment]
the above had lots of transparency issue. finalized palette for buttons is below: 


![Image](https://user-images.githubusercontent.com/33136939/214334237-937a7b6c-79ea-4564-91d1-31a12f697b27.png)
